version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gofmt
    - unused

linters-settings: {}

issues:
  exclude-use-default: false
  exclude-rules:
    - path: internal/storage/s3client/client.go
      text: "SA1019"
