replicaCount: 2

image:
  tag: v0.2.3

ingress:
  host: invent-back.jcrlabs.net

config:
  minioPublicUrl: https://minio.jcrlabs.net

postgres:
  storage: 10Gi

minio:
  storage: 20Gi
  ingress:
    host: minio.jcrlabs.net

hpa:
  minReplicas: 2
  maxReplicas: 5
