apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    {{- include "inventory-back.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: MINIO_SECRET_KEY
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 15
          volumeMounts:
            - mountPath: /data
              name: minio-data
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
