apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels:
    {{- include "inventory-back.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storage }}
